[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Cache static assets with shorter cache time for logos
[[headers]]
  for = "/logo.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"  # 1 hour instead of 1 year

[[headers]]
  for = "/codarambha-logo.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"  # 1 hour

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"  # 1 day instead of 1 year
